<?php

namespace Tests;

use App\Models\Season;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase;

    /**
     * @var \App\Models\Season
     */
    protected $season;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->refreshTestDatabase();

        $this->createSeason();
    }

    /**
     * Create a season for the backoffice.
     *
     * @return void
     */
    protected function createSeason()
    {
        $this->season = Season::factory()->create();
    }
}
